version: '3.8'

services:
  # Node.js 서비스 정의
  nodejs_app:
    build: ./nodejs # 'nodejs' 폴더의 Dockerfile을 참조
    container_name: my_nodejs_service
    ports:
      - "8000:8000" # 호스트의 8000 포트를 컨테이너의 8000 포트에 연결
    volumes:
      - ./nodejs:/app # 개발 중 소스 코드 변경 사항 반영
      - /app/node_modules # 컨테이너 내부의 node_modules는 호스트와 분리

  # Python (FastAPI) 서비스 정의
  python_app:
    build: ./python # 'python' 폴더의 Dockerfile을 참조
    container_name: my_fastapi_service
    # Node.js와 포트 충돌 방지를 위해 호스트 포트를 다르게 설정 (예: 8001)
    ports:
      - "8001:3000" # 호스트의 8001 포트를 컨테이너의 3000 포트에 연결 (FastAPI EXPOSE 3000에 맞춤)
    volumes:
      - ./python:/app # 개발 중 소스 코드 변경 사항 반영